server_address: ws://127.0.0.1:5465/
listen: false
token: xxx
keepalive: 100
network:
  -
    network: default
    interface: wg0
    id: 2
    peers:
      -
        id: 3
        persistent_keepalive: 25
